version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-voz-cidada
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=voz-cidada
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/voz-cidada
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    volumes:
      - uploads-data:/app/uploads

  web:
    build: client
    ports:
      - "5173:80"
    depends_on:
      - app

volumes:
  postgres-data:
  uploads-data:
