services:
  app:
    build: server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/voz-cidada
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    volumes:
      - uploads-data:/app/uploads

  web:
    build: client
    ports:
      - "5173:80"
    depends_on:
      - app

volumes:
  postgres-data:
  uploads-data: