services:
  postgres:
    image: postgres:16
    container_name: postgres-voz-cidada
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=voz-cidada
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: