cors:
  originPatterns: https://localhost:8080,http://localhost:5173
spring:
  application:
    name: "Voz Cidadã"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/voz-cidada
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
security:
  token:
    secret: ${JWT_SECRET:default-secret}
    expire-length: 3600
server:
  port: 8080
app:
  upload:
    dir: "/app/uploads"