spring:
  application:
    name: "Voz Cidadã"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/voz-cidada
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
security:
  token:
    secret: ${JWT_SECRET:default-secret}
    expires-in: 86400000