spring:
  application:
    name: "Voz Cidadã"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/voz-cidada
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
security:
  token:
    secret: ${JWT_SECRET:default-secret}
    expire-length: 3600